### ISSUE TITLE
Timezones

### ISSUE THREAD

**Issue by sebj54** [cynthiapereira/webextension-gradientus#1]
Hi! Thanks for your nice extension :)
Do you handle timezones? It's actually 12:11 AM in France and I'm seeing night theme :(

**Comment by cpswsg** [comment]
Hi there!
I am using `newDate()` to get the local time but I realized now that my "afternoon hours" does not look like as an afternoon properly. So I will change it and add a new theme for wee hours. Also, please see #2.

**Comment by sebj54** [comment]
Hi there, thanks for replying and fixing this!
Actually, it does not look resolved to me :(

Today at 12AM (12:00, still in France), the dawn theme suddenly appeared. At 1PM (13:00), theme changed for afternoon. 
Was there something wrong with the update?

**Comment by cpswsg** [comment]
@sebj54 You're right!

I forgot to setup the logical conditional in these hours. So here it is how the extension should works:
```
Morning – 6:00 to 12:59
Afternoon – 13:00 to 18:59
Night – 19:00 to 3:59
Dawn – 4:00 to 5:59
```
A new update will be available in a few hours. 

Thanks so much!

**Comment by sebj54** [comment]
You're welcome! It works very well now :)
