### ISSUE TITLE
Unfocused tab titles are black text instead of gray text in Firefox 70

### ISSUE THREAD

**Issue by cpeterso** [cynthiapereira/webextension-gradientus#10]
The unfocused tabs' titles are very hard to read because they are black text on a color background instead of gray text. Screenshot:

![image](https://user-images.githubusercontent.com/629193/61655879-4a0c1380-ac74-11e9-8bf2-d80c9882c5a5.png)

Firefox 70 removed some [theme property names that were deprecated in Firefox 69](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme#Aliases):

> Beginning in Firefox 69, the following properties will be deprecated: toolbar_text, accentcolor, and textcolor. Use bookmark_text, frame, frame_inactive, and tab_background_text instead. Using these values in themes loaded into Firefox 65 or later will raise warnings.

Gradientus uses some of these property aliases:

https://github.com/cynthiapereira/webextension-gradientus/blob/5664eb9896288acf6ae04757977efdd35f51e99e/src/gradientus.js#L13-L23

Here's a fix for Mozilla's FirefoxColor theme generator: mozilla/FirefoxColor#763

**Comment by cpswsg** [comment]
An update will be available soon. Thank you!

**Comment by cpeterso** [comment]
Awesome! Thank you! 😄
