### ISSUE TITLE
What Time Do These Activate?

### ISSUE THREAD

**Issue by SocietasEvanescentes** [cynthiapereira/webextension-gradientus#2]
Not really an issue, but more of a question. I'm curious to see when it changes. Good job btw!

**Comment by cpswsg** [comment]
Hi!
Until now: `morning – 6:00am to 12:59pm`,  `afternoon – 1:00am to 22:59pm` and `night – 23:00pm to 5:59am`. But I will add a new theme for wee hours and change the afternoon based on this #1 feedback. =)
